# Generated by Django 4.0.1 on 2022-02-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('latex', models.JSONField()),
                ('html', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('logs', models.JSONField()),
            ],
        ),
    ]
