# Generated by Django 4.0.1 on 2022-02-17 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_user_log_logs_user_log_ip_user_log_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 17, 23, 50, 319561)),
        ),
    ]
