# Generated by Django 4.0.1 on 2022-08-07 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_user_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 3, 4, 39, 623912)),
        ),
    ]
